[package]
name = "galaxy-buds-gui-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.10", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.8", features = ["v1_7"] }